import type { Language } from './types'

export interface CurriculumProfile { id: string; level: string; course: string; subject: string; labels: Record<Language, string> }
export interface CurriculumElements { specificCompetences: string[]; assessmentCriteria: string[]; basicKnowledge: string[] }
const profile = (id: string, level: string, course: string, subject: string, es: string, ca: string, en = es): CurriculumProfile => ({ id, level, course, subject, labels: { es, 'ca-valencia': ca, ca, en } })

// Catálogo inicial CV-LOMLOE. Los elementos curriculares detallados se incorporarán
// como una segunda capa versionada, sin bloquear el uso general de la aplicación.
export const valencianProfiles: CurriculumProfile[] = [
  profile('cv-infantil', 'Infantil', '2n cicle d’Educació Infantil', '', 'Comunitat Valenciana · Infantil (2.º ciclo)', 'Comunitat Valenciana · Infantil (2n cicle)', 'Valencian Community · Early childhood (2nd cycle)'),
  profile('cv-primaria', 'Primaria', 'Educació Primària', '', 'Comunitat Valenciana · Educación Primaria', 'Comunitat Valenciana · Educació Primària', 'Valencian Community · Primary education'),
  ...[['Coneixement del medi natural, social i cultural', 'Coneixement del medi natural, social i cultural'], ['Educació artística', 'Educació artística'], ['Educació física', 'Educació física'], ['Llengua castellana i literatura', 'Llengua castellana i literatura'], ['Valencià: llengua i literatura', 'Valencià: llengua i literatura'], ['Llengua estrangera', 'Llengua estrangera'], ['Matemàtiques', 'Matemàtiques'], ['Educació en valors cívics i ètics', 'Educació en valors cívics i ètics']].map(([subject, valencian]) => profile(`cv-primaria-${subject.toLowerCase().replace(/[^a-zà-ÿ]+/g, '-')}`, 'Primaria', 'Educació Primària', subject, `Comunitat Valenciana · Primaria · ${subject}`, `Comunitat Valenciana · Primària · ${valencian}`)),
  ...[['Biologia i Geologia', 'Biologia i Geologia'], ['Física i Química', 'Física i Química'], ['Geografia i Història', 'Geografia i Història'], ['Llengua Castellana i Literatura', 'Llengua Castellana i Literatura'], ['Valencià: Llengua i Literatura', 'Valencià: Llengua i Literatura'], ['Llengua Estrangera', 'Llengua Estrangera'], ['Matemàtiques', 'Matemàtiques'], ['Matemàtiques A', 'Matemàtiques A'], ['Matemàtiques B', 'Matemàtiques B'], ['Tecnologia i Digitalització', 'Tecnologia i Digitalització'], ['Digitalització', 'Digitalització'], ['Educació Física', 'Educació Física'], ['Educació Plàstica, Visual i Audiovisual', 'Educació Plàstica, Visual i Audiovisual'], ['Música', 'Música'], ['Economia i Emprenedoria', 'Economia i Emprenedoria'], ['Formació i Orientació Personal i Professional', 'Formació i Orientació Personal i Professional'], ['Llatí', 'Llatí'], ['Segona Llengua Estrangera', 'Segona Llengua Estrangera'], ['Filosofia', 'Filosofia']].map(([subject, valencian]) => profile(`cv-eso-${subject.toLowerCase().replace(/[^a-zà-ÿ]+/g, '-')}`, 'ESO', 'ESO', subject, `Comunitat Valenciana · ESO · ${subject}`, `Comunitat Valenciana · ESO · ${valencian}`)),
  ...[['Filosofia', 'Filosofia'], ['Història d’Espanya', 'Història d’Espanya'], ['Història de la Filosofia', 'Història de la Filosofia'], ['Llengua Castellana i Literatura', 'Llengua Castellana i Literatura'], ['Valencià: Llengua i Literatura', 'Valencià: Llengua i Literatura'], ['Llengua Estrangera', 'Llengua Estrangera'], ['Educació Física', 'Educació Física'], ['Matemàtiques I', 'Matemàtiques I'], ['Matemàtiques II', 'Matemàtiques II'], ['Matemàtiques Aplicades a les Ciències Socials I', 'Matemàtiques Aplicades a les Ciències Socials I'], ['Matemàtiques Aplicades a les Ciències Socials II', 'Matemàtiques Aplicades a les Ciències Socials II'], ['Biologia', 'Biologia'], ['Física', 'Física'], ['Química', 'Química'], ['Geologia i Ciències Ambientals', 'Geologia i Ciències Ambientals'], ['Dibuix Tècnic', 'Dibuix Tècnic'], ['Tecnologia i Enginyeria', 'Tecnologia i Enginyeria'], ['Economia', 'Economia'], ['Geografia', 'Geografia'], ['Història de l’Art', 'Història de l’Art'], ['Literatura Universal', 'Literatura Universal'], ['Anàlisi Musical', 'Anàlisi Musical'], ['Arts Escèniques', 'Arts Escèniques'], ['Segona Llengua Estrangera', 'Segona Llengua Estrangera']].map(([subject, valencian]) => profile(`cv-batx-${subject.toLowerCase().replace(/[^a-zà-ÿ]+/g, '-')}`, 'Bachillerato', 'Batxillerat', subject, `Comunitat Valenciana · Bachillerato · ${subject}`, `Comunitat Valenciana · Batxillerat · ${valencian}`)),
  profile('cv-fp', 'Formación Profesional', 'Cicle formatiu', '', 'Comunitat Valenciana · Formación Profesional', 'Comunitat Valenciana · Formació Professional', 'Valencian Community · Vocational education'),
  profile('cv-adults', 'Educación de personas adultas', 'Formació de persones adultes', '', 'Comunitat Valenciana · Educación de personas adultas', 'Comunitat Valenciana · Educació de persones adultes', 'Valencian Community · Adult education')
]

// Primera colección curricular detallada. Son opciones de apoyo para redactar el
// prompt; el profesorado puede editarlas y no sustituyen la programación oficial.
export const valencianCurriculumElements: Record<string, CurriculumElements> = {
  'cv-eso-tecnologia-i-digitalització': {
    specificCompetences: ['Identificar i resoldre problemes tecnològics de manera planificada.', 'Analitzar objectes i sistemes tecnològics aplicant criteris de sostenibilitat.', 'Desenvolupar solucions digitals i de programació per a necessitats concretes.', 'Comunicar i documentar el procés de disseny, construcció i avaluació.'],
    assessmentCriteria: ['Defineix el problema i proposa una solució viable.', 'Planifica, construeix i prova un prototip amb seguretat.', 'Utilitza materials, eines i recursos digitals de manera responsable.', 'Documenta el procés i justifica les decisions preses.'],
    basicKnowledge: ['Procés de resolució de problemes tecnològics.', 'Materials, estructures i mecanismes.', 'Electricitat i electrònica.', 'Programació, control i robòtica.', 'Tecnologia digital, dades i ciutadania digital.', 'Sostenibilitat i impacte social de la tecnologia.']
  },
  'cv-eso-matemàtiques': {
    specificCompetences: ['Interpretar i resoldre problemes matemàtics en contextos diversos.', 'Explorar, formular i validar conjectures amb raonament matemàtic.', 'Representar i comunicar idees matemàtiques amb llenguatges diversos.', 'Utilitzar eines tecnològiques per investigar i comprovar resultats.'],
    assessmentCriteria: ['Comprén la situació i selecciona estratègies adequades.', 'Realitza representacions i connexions entre conceptes.', 'Justifica el procés i comprova la validesa del resultat.', 'Comunica conclusions amb precisió i vocabulari matemàtic.'],
    basicKnowledge: ['Sentit numèric i de les operacions.', 'Sentit algebraic.', 'Sentit espacial i geomètric.', 'Relacions i funcions.', 'Sentit estocàstic.', 'Pensament computacional.']
  }
}
