import type { Language, PromptTemplate } from './types'
import { localizeOption } from './optionLocales'

type LabelKey = 'role'|'context'|'task'|'objectives'|'methodology'|'duration'|'resources'|'requirements'|'format'|'criteria'|'qualityCriteria'|'constraints'|'levels'|'activityType'|'specificCompetences'|'assessmentCriteria'|'basicKnowledge'
type DefaultText = 'role'|'education'|'stage'|'design'|'rubric'|'checklist'|'h5p'|'interactive'|'topic'|'draft'|'clear'|'viable'|'verify'|'invent'|'structured'
const labels: Record<Language, Record<LabelKey,string>> = {
  es:{role:'Rol',context:'Contexto',task:'Objetivo y tarea',objectives:'Objetivos',methodology:'Metodología',duration:'Duración',resources:'Recursos disponibles',requirements:'Revisión docente',format:'Formato de salida',criteria:'Criterios',qualityCriteria:'Criterios de calidad',constraints:'Restricciones y límites',levels:'Niveles de desempeño',activityType:'Tipo de actividad',specificCompetences:'Competencias específicas',assessmentCriteria:'Criterios de evaluación',basicKnowledge:'Saberes básicos'},
  'ca-valencia':{role:'Rol',context:'Context',task:'Objectiu i tasca',objectives:'Objectius',methodology:'Metodologia',duration:'Duració',resources:'Recursos disponibles',requirements:'Revisió docent',format:'Format d’eixida',criteria:'Criteris',qualityCriteria:'Criteris de qualitat',constraints:'Restriccions i límits',levels:'Nivells de rendiment',activityType:'Tipus d’activitat',specificCompetences:'Competències específiques',assessmentCriteria:'Criteris d’avaluació',basicKnowledge:'Sabers bàsics'},
  ca:{role:'Rol',context:'Context',task:'Objectiu i tasca',objectives:'Objectius',methodology:'Metodologia',duration:'Durada',resources:'Recursos disponibles',requirements:'Revisió docent',format:'Format de sortida',criteria:'Criteris',qualityCriteria:'Criteris de qualitat',constraints:'Restriccions i límits',levels:'Nivells de rendiment',activityType:'Tipus d’activitat',specificCompetences:'Competències específiques',assessmentCriteria:'Criteris d’avaluació',basicKnowledge:'Sabers bàsics'},
  en:{role:'Role',context:'Context',task:'Objective and task',objectives:'Objectives',methodology:'Methodology',duration:'Duration',resources:'Available resources',requirements:'Teacher review',format:'Output format',criteria:'Criteria',qualityCriteria:'Quality criteria',constraints:'Constraints and limits',levels:'Performance levels',activityType:'Activity type',specificCompetences:'Specific competences',assessmentCriteria:'Assessment criteria',basicKnowledge:'Basic knowledge'}
}
const defaults: Record<Language, Record<DefaultText,string>> = {
  es:{role:'Actúa como docente especialista en',education:'educación y diseño de actividades para alumnado de',stage:'la etapa indicada',design:'Diseña una actividad sobre',rubric:'Crea una rúbrica para evaluar',checklist:'Crea una lista de cotejo para',h5p:'Diseña una actividad H5P de tipo',interactive:'interactivo',topic:'el tema indicado',draft:'Entrega un primer borrador revisable, no lo presentes como definitivo.',clear:'Usa instrucciones claras, observables y adecuadas al nivel.',viable:'Comprueba que la propuesta es viable con el tiempo y los recursos indicados.',verify:'Señala cualquier dato, fuente o supuesto que deba verificar la persona docente.',invent:'No inventes normativa, referencias ni información sobre el alumnado.',structured:'texto estructurado'},
  'ca-valencia':{role:'Actua com a docent especialista en',education:'educació i disseny d’activitats per a alumnat de',stage:'l’etapa indicada',design:'Dissenya una activitat sobre',rubric:'Crea una rúbrica per a avaluar',checklist:'Crea una llista de verificació per a',h5p:'Dissenya una activitat H5P de tipus',interactive:'interactiu',topic:'el tema indicat',draft:'Entrega un primer esborrany revisable, no el presentes com a definitiu.',clear:'Usa instruccions clares, observables i adequades al nivell.',viable:'Comprova que la proposta és viable amb el temps i els recursos indicats.',verify:'Assenyala qualsevol dada, font o supòsit que haja de verificar la persona docent.',invent:'No inventes normativa, referències ni informació sobre l’alumnat.',structured:'text estructurat'},
  ca:{role:'Actua com a docent especialista en',education:'educació i disseny d’activitats per a alumnat de',stage:'l’etapa indicada',design:'Dissenya una activitat sobre',rubric:'Crea una rúbrica per avaluar',checklist:'Crea una llista de verificació per a',h5p:'Dissenya una activitat H5P de tipus',interactive:'interactiu',topic:'el tema indicat',draft:'Ofereix un primer esborrany revisable, no el presentis com a definitiu.',clear:'Utilitza instruccions clares, observables i adequades al nivell.',viable:'Comprova que la proposta és viable amb el temps i els recursos indicats.',verify:'Assenyala qualsevol dada, font o supòsit que hagi de verificar el docent.',invent:'No inventis normativa, referències ni informació sobre l’alumnat.',structured:'text estructurat'},
  en:{role:'Act as a teacher specialising in',education:'education and activity design for learners at',stage:'the stated educational stage',design:'Design an activity about',rubric:'Create a rubric to assess',checklist:'Create a checklist for',h5p:'Design an H5P activity of type',interactive:'interactive',topic:'the stated topic',draft:'Deliver a reviewable first draft; do not present it as definitive.',clear:'Use clear, observable instructions appropriate to the level.',viable:'Check that the proposal is feasible with the stated time and resources.',verify:'Flag any data, source or assumption the teacher should verify.',invent:'Do not invent regulations, references or information about learners.',structured:'structured text'}
}

export function generatePrompt(template: PromptTemplate, values: Record<string,string>, language: Language): string {
  const l=labels[language]
  const d=defaults[language]
  const localizedKeys = new Set(['level', 'methodology', 'duration', 'resources', 'outputFormat', 'activityType'])
  const value=(key:string)=>{const raw=values[key]?.trim()||'';return localizedKeys.has(key)?raw.split(' · ').map(item=>localizeOption(item,language)).join(' · '):raw}
  const lines:string[]=[]
  const level=[value('level'),value('course')].filter(Boolean).join(' ')
  lines.push(`## ${l.role}\n${value('role')||`${d.role} ${value('subject')||d.education} ${level||d.stage}.`}`)
  if(value('context')||level||value('curriculumContext')) lines.push(`## ${l.context}\n${level?`Trabajo con alumnado de ${level}.`:''}\n${value('curriculumContext')}\n${value('context')}`.trim())
  if(value('curriculumCompetences')) lines.push(`## ${l.specificCompetences}\n${value('curriculumCompetences')}`)
  const task = template.id==='rubric'?`${d.rubric} ${value('activity')||d.topic}.`:template.id==='checklist'?`${d.checklist} ${value('activity')||d.topic}.`:template.id==='h5p'?`${d.h5p} ${value('activityType')||d.interactive} ${language==='en'?'about':'sobre'} ${value('topic')||d.topic}.`:value('task')||`${d.design} ${value('topic')||d.topic}.`
  lines.push(`## ${l.task}\n${task}`)
  for(const key of ['objectives','criteria','methodology','duration','resources','levels','constraints','qualityCriteria']) if(value(key)) lines.push(`## ${l[key as LabelKey]}\n${value(key)}`)
  if(value('curriculumCriteria')) lines.push(`## ${l.assessmentCriteria}\n${value('curriculumCriteria')}`)
  if(value('curriculumKnowledge')) lines.push(`## ${l.basicKnowledge}\n${value('curriculumKnowledge')}`)
  const returnText = language === 'en' ? 'Return the result in' : language === 'es' ? 'Devuelve el resultado en' : language === 'ca-valencia' ? 'Retorna el resultat en' : 'Retorna el resultat en'
  lines.push(`## ${l.requirements}\n- ${d.draft}\n- ${d.clear}\n- ${d.viable}\n- ${d.verify}\n- ${d.invent}`, `## ${l.format}\n${returnText} ${value('outputFormat')||d.structured}.`)
  return lines.join('\n\n')
}
