import type { Language } from './types'
export const translations: Record<Language, Record<string,string>> = {
  es: {app:'EduTicTac Prompt', tagline:'Crea mejores prompts educativos, sin complicaciones.',home:'Inicio',create:'Crear',library:'Mi biblioteca',privacy:'Privacidad',about:'Acerca de',search:'Buscar herramienta...',all:'Todas',planning:'Planificación docente',activities:'Actividades',assessment:'Evaluación',adaptation:'Adaptación',content:'Contenidos',digital:'Recursos digitales',communication:'Comunicación',free:'Constructor libre',generate:'Generar prompt',preview:'Vista previa del prompt',copy:'Copiar',save:'Guardar',clear:'Limpiar',saved:'Guardado',noPrompts:'Aún no tienes prompts guardados.',librarySearch:'Buscar en mi biblioteca...',title:'Título',category:'Categoría',tags:'Etiquetas (separadas por comas)',notes:'Notas',favorite:'Favorito',cancel:'Cancelar',confirm:'Guardar prompt',export:'Exportar',import:'Importar',delete:'Eliminar',duplicate:'Duplicar',language:'Idioma',theme:'Tema',system:'Automático',light:'Claro',dark:'Oscuro',warning:'No introduzcas nombres, datos personales ni información sensible del alumnado.',empty:'Completa el formulario para generar tu prompt.',savedOk:'Prompt guardado en tu biblioteca.',importOk:'Importación completada.',choose:'Elige una herramienta',privacyText:'Tus prompts se guardan inicialmente en este dispositivo mediante IndexedDB. No se envían automáticamente a ningún servicio y generar un prompt no llama a ninguna IA.'},
  'ca-valencia': {app:'EduTicTac Prompt',tagline:'Crea millors prompts educatius, sense complicacions.',home:'Inici',create:'Crear',library:'La meua biblioteca',privacy:'Privacitat',about:'Quant a',search:'Buscar ferramenta...',all:'Totes',planning:'Planificació docent',activities:'Activitats',assessment:'Avaluació',adaptation:'Adaptació',content:'Continguts',digital:'Recursos digitals',communication:'Comunicació',free:'Constructor lliure',generate:'Generar prompt',preview:'Vista prèvia del prompt',copy:'Copiar',save:'Guardar',clear:'Netejar',saved:'Guardat',noPrompts:'Encara no tens prompts guardats.',librarySearch:'Buscar en la meua biblioteca...',title:'Títol',category:'Categoria',tags:'Etiquetes (separades per comes)',notes:'Notes',favorite:'Favorit',cancel:'Cancel·lar',confirm:'Guardar prompt',export:'Exportar',import:'Importar',delete:'Eliminar',duplicate:'Duplicar',language:'Idioma',theme:'Tema',system:'Automàtic',light:'Clar',dark:'Fosc',warning:'No introduïsques noms, dades personals ni informació sensible de l’alumnat.',empty:'Completa el formulari per a generar el teu prompt.',savedOk:'Prompt guardat en la teua biblioteca.',importOk:'Importació completada.',choose:'Tria una ferramenta',privacyText:'Els teus prompts es guarden inicialment en este dispositiu mitjançant IndexedDB. No s’envien automàticament a cap servici i generar un prompt no crida cap IA.'},
  ca: {app:'EduTicTac Prompt',tagline:'Crea millors prompts educatius, sense complicacions.',home:'Inici',create:'Crear',library:'La meva biblioteca',privacy:'Privacitat',about:'Quant a',search:'Cerca una eina...',all:'Totes',planning:'Planificació docent',activities:'Activitats',assessment:'Avaluació',adaptation:'Adaptació',content:'Continguts',digital:'Recursos digitals',communication:'Comunicació',free:'Constructor lliure',generate:'Genera el prompt',preview:'Vista prèvia del prompt',copy:'Copia',save:'Desa',clear:'Neteja',saved:'Desat',noPrompts:'Encara no tens prompts desats.',librarySearch:'Cerca a la meva biblioteca...',title:'Títol',category:'Categoria',tags:'Etiquetes (separades per comes)',notes:'Notes',favorite:'Preferit',cancel:'Cancel·la',confirm:'Desa el prompt',export:'Exporta',import:'Importa',delete:'Elimina',duplicate:'Duplica',language:'Llengua',theme:'Tema',system:'Automàtic',light:'Clar',dark:'Fosc',warning:'No introdueixis noms, dades personals ni informació sensible de l’alumnat.',empty:'Completa el formulari per generar el teu prompt.',savedOk:'Prompt desat a la teva biblioteca.',importOk:'Importació completada.',choose:'Tria una eina',privacyText:'Els teus prompts es desen inicialment en aquest dispositiu mitjançant IndexedDB. No s’envien automàticament a cap servei i generar un prompt no crida cap IA.'},
  en: {app:'EduTicTac Prompt',tagline:'Create better educational prompts, simply.',home:'Home',create:'Create',library:'My library',privacy:'Privacy',about:'About',search:'Search tools...',all:'All',planning:'Lesson planning',activities:'Activities',assessment:'Assessment',adaptation:'Adaptation',content:'Content',digital:'Digital resources',communication:'Communication',free:'Free builder',generate:'Generate prompt',preview:'Prompt preview',copy:'Copy',save:'Save',clear:'Clear',saved:'Saved',noPrompts:'You have no saved prompts yet.',librarySearch:'Search my library...',title:'Title',category:'Category',tags:'Tags (comma separated)',notes:'Notes',favorite:'Favorite',cancel:'Cancel',confirm:'Save prompt',export:'Export',import:'Import',delete:'Delete',duplicate:'Duplicate',language:'Language',theme:'Theme',system:'Automatic',light:'Light',dark:'Dark',warning:'Do not enter names, personal data or sensitive student information.',empty:'Complete the form to generate your prompt.',savedOk:'Prompt saved to your library.',importOk:'Import complete.',choose:'Choose a tool',privacyText:'Your prompts are initially stored on this device using IndexedDB. They are not automatically sent to any service and generating a prompt does not call an AI.'}
}
for (const language of ['es', 'ca-valencia', 'ca', 'en'] as Language[]) {
  Object.assign(translations[language], {
    curriculum: language === 'en' ? 'Curriculum profile (optional)' : 'Perfil curricular (opcional)',
    general: language === 'en' ? 'General mode: no curriculum profile' : language === 'ca-valencia' ? 'Mode general: sense perfil curricular' : language === 'ca' ? 'Mode general: sense perfil curricular' : 'Modo general: sin perfil curricular'
  })
}
export function detectLanguage(): Language { const value = localStorage.getItem('edutictac-language'); if (value === 'es'||value === 'ca'||value === 'ca-valencia'||value === 'en') return value; const browser = navigator.language.toLowerCase(); return browser.startsWith('en')?'en':browser.startsWith('ca')?'ca': 'es' }
