import type { Language } from './types'
export const translations: Record<Language, Record<string,string>> = {
  es: {app:'EduTicTac Prompt', tagline:'Crea mejores prompts educativos, sin complicaciones.',toolsCount:'24 herramientas educativas en evolución',home:'Inicio',create:'Crear',library:'Mi biblioteca',privacy:'Privacidad',about:'Acerca de',search:'Buscar herramienta...',all:'Todas',planning:'Planificación docente',activities:'Actividades',assessment:'Evaluación',adaptation:'Adaptación',content:'Contenidos',digital:'Recursos digitales',communication:'Comunicación',free:'Constructor libre',generate:'Generar prompt',preview:'Vista previa del prompt',copy:'Copiar',save:'Guardar',clear:'Limpiar',saved:'Guardado',noPrompts:'Aún no tienes prompts guardados.',librarySearch:'Buscar en mi biblioteca...',title:'Título',category:'Categoría',tags:'Etiquetas (separadas por comas)',notes:'Notas',favorite:'Favorito',cancel:'Cancelar',confirm:'Guardar prompt',export:'Exportar',import:'Importar',delete:'Eliminar',duplicate:'Duplicar',language:'Idioma',theme:'Tema',system:'Automático',light:'Claro',dark:'Oscuro',warning:'No introduzcas nombres, datos personales ni información sensible del alumnado.',empty:'Completa el formulario para generar tu prompt.',savedOk:'Prompt guardado en tu biblioteca.',importOk:'Importación completada.',choose:'Elige una herramienta',privacyText:'Tus prompts se guardan inicialmente en este dispositivo mediante IndexedDB. No se envían automáticamente a ningún servicio y generar un prompt no llama a ninguna IA.'},
  'ca-valencia': {app:'EduTicTac Prompt',tagline:'Crea millors prompts educatius, sense complicacions.',toolsCount:'24 ferramentes educatives en evolució',home:'Inici',create:'Crear',library:'La meua biblioteca',privacy:'Privacitat',about:'Quant a',search:'Buscar ferramenta...',all:'Totes',planning:'Planificació docent',activities:'Activitats',assessment:'Avaluació',adaptation:'Adaptació',content:'Continguts',digital:'Recursos digitals',communication:'Comunicació',free:'Constructor lliure',generate:'Generar prompt',preview:'Vista prèvia del prompt',copy:'Copiar',save:'Guardar',clear:'Netejar',saved:'Guardat',noPrompts:'Encara no tens prompts guardats.',librarySearch:'Buscar en la meua biblioteca...',title:'Títol',category:'Categoria',tags:'Etiquetes (separades per comes)',notes:'Notes',favorite:'Favorit',cancel:'Cancel·lar',confirm:'Guardar prompt',export:'Exportar',import:'Importar',delete:'Eliminar',duplicate:'Duplicar',language:'Idioma',theme:'Tema',system:'Automàtic',light:'Clar',dark:'Fosc',warning:'No introduïsques noms, dades personals ni informació sensible de l’alumnat.',empty:'Completa el formulari per a generar el teu prompt.',savedOk:'Prompt guardat en la teua biblioteca.',importOk:'Importació completada.',choose:'Tria una ferramenta',privacyText:'Els teus prompts es guarden inicialment en este dispositiu mitjançant IndexedDB. No s’envien automàticament a cap servici i generar un prompt no crida cap IA.'},
  ca: {app:'EduTicTac Prompt',tagline:'Crea millors prompts educatius, sense complicacions.',toolsCount:'24 eines educatives en evolució',home:'Inici',create:'Crear',library:'La meva biblioteca',privacy:'Privacitat',about:'Quant a',search:'Cerca una eina...',all:'Totes',planning:'Planificació docent',activities:'Activitats',assessment:'Avaluació',adaptation:'Adaptació',content:'Continguts',digital:'Recursos digitals',communication:'Comunicació',free:'Constructor lliure',generate:'Genera el prompt',preview:'Vista prèvia del prompt',copy:'Copia',save:'Desa',clear:'Neteja',saved:'Desat',noPrompts:'Encara no tens prompts desats.',librarySearch:'Cerca a la meva biblioteca...',title:'Títol',category:'Categoria',tags:'Etiquetes (separades per comes)',notes:'Notes',favorite:'Preferit',cancel:'Cancel·la',confirm:'Desa el prompt',export:'Exporta',import:'Importa',delete:'Elimina',duplicate:'Duplica',language:'Llengua',theme:'Tema',system:'Automàtic',light:'Clar',dark:'Fosc',warning:'No introdueixis noms, dades personals ni informació sensible de l’alumnat.',empty:'Completa el formulari per generar el teu prompt.',savedOk:'Prompt desat a la teva biblioteca.',importOk:'Importació completada.',choose:'Tria una eina',privacyText:'Els teus prompts es desen inicialment en aquest dispositiu mitjançant IndexedDB. No s’envien automàticament a cap servei i generar un prompt no crida cap IA.'},
  en: {app:'EduTicTac Prompt',tagline:'Create better educational prompts, simply.',toolsCount:'24 educational tools and growing',home:'Home',create:'Create',library:'My library',privacy:'Privacy',about:'About',search:'Search tools...',all:'All',planning:'Lesson planning',activities:'Activities',assessment:'Assessment',adaptation:'Adaptation',content:'Content',digital:'Digital resources',communication:'Communication',free:'Free builder',generate:'Generate prompt',preview:'Prompt preview',copy:'Copy',save:'Save',clear:'Clear',saved:'Saved',noPrompts:'You have no saved prompts yet.',librarySearch:'Search my library...',title:'Title',category:'Category',tags:'Tags (comma separated)',notes:'Notes',favorite:'Favorite',cancel:'Cancel',confirm:'Save prompt',export:'Export',import:'Import',delete:'Delete',duplicate:'Duplicate',language:'Language',theme:'Theme',system:'Automatic',light:'Light',dark:'Dark',warning:'Do not enter names, personal data or sensitive student information.',empty:'Complete the form to generate your prompt.',savedOk:'Prompt saved to your library.',importOk:'Import complete.',choose:'Choose a tool',privacyText:'Your prompts are initially stored on this device using IndexedDB. They are not automatically sent to any service and generating a prompt does not call an AI.'}
}
for (const language of ['es', 'ca-valencia', 'ca', 'en'] as Language[]) {
  Object.assign(translations[language], {
    curriculum: language === 'en' ? 'Curriculum profile (optional)' : 'Perfil curricular (opcional)',
    general: language === 'en' ? 'General mode: no curriculum profile' : language === 'ca-valencia' ? 'Mode general: sense perfil curricular' : language === 'ca' ? 'Mode general: sense perfil curricular' : 'Modo general: sin perfil curricular',
    specificCompetences: language === 'en' ? 'Specific competences' : language === 'ca' ? 'Competències específiques' : 'Competències específiques',
    assessmentCriteria: language === 'en' ? 'Assessment criteria' : language === 'ca' ? 'Criteris d’avaluació' : 'Criteris d’avaluació',
    basicKnowledge: language === 'en' ? 'Basic knowledge' : 'Sabers bàsics',
    lead: language === 'en' ? 'Shape your classroom ideas with guided forms. Your data stays on your device.' : language === 'ca' ? 'Dona forma a les teves idees per a l’aula amb formularis guiats. Les teves dades romanen al teu dispositiu.' : 'Dona forma a les teues idees per a l’aula amb formularis guiats. Les teues dades romanen en el teu dispositiu.',
    catalog: language === 'en' ? 'CATALOGUE' : 'CATÀLEG',
    privacyTitle: language === 'en' ? 'Privacy and responsible use' : language === 'ca' ? 'Privacitat i ús responsable' : 'Privacitat i ús responsable',
    privacyHeading: language === 'en' ? 'A tool at the service of teachers' : language === 'ca' ? 'Una eina al servei del professorat' : 'Una ferramenta al servici del professorat',
    privacyBody: language === 'en' ? 'Always review AI responses, verify references and facts, check for possible bias, and adapt materials to your context. Do not automatically use responses for grading. Teaching responsibility always remains with you.' : language === 'ca' ? 'Revisa sempre les respostes de qualsevol IA, verifica referències i dades, comprova possibles biaixos i adapta els materials al teu context. No utilitzis automàticament les respostes per a qualificar. La responsabilitat docent sempre és teva.' : 'Revisa sempre les respostes de qualsevol IA, verifica referències i dades, comprova possibles biaixos i adapta els materials al teu context. No utilitzes automàticament les respostes per a qualificar. La responsabilitat docent sempre és teua.',
    offline: language === 'en' ? 'Works without an account or connection' : language === 'ca' ? 'Funciona sense compte i sense connexió' : 'Funciona sense compte i sense connexió',
    localStatus: language === 'en' ? '● local' : '● local',
    topicHint: language === 'en' ? 'Describe specifically what you want to work on.' : language === 'ca' ? 'Descriu concretament què vols treballar.' : 'Descriu de manera concreta què vols treballar.',
    topicSuggestionsHint: language === 'en' ? 'You can write your own topic or choose a suggestion from basic knowledge.' : language === 'es' ? 'Puedes escribir tu propio tema o elegir una sugerencia de los saberes básicos.' : 'Pots escriure el teu tema o triar un suggeriment dels sabers bàsics.',
    curriculumElements: language === 'en' ? 'Optional curriculum elements' : 'Elements curriculars opcionals',
    curriculumElementsHint: language === 'en' ? 'Select the elements you want the prompt to work on. Hold Ctrl or Cmd to select several.' : language === 'es' ? 'Selecciona los elementos que quieres trabajar. Mantén Ctrl o Cmd para elegir varios.' : 'Selecciona els elements que vols treballar. Mantín premuda la tecla Ctrl o Cmd per a triar-ne diversos.',
    subjectsForStage: language === 'en' ? 'Subjects for this stage' : 'Matèries disponibles per a esta etapa',
    subjectHint: language === 'en' ? 'Optional suggestion; the free subject field remains available below.' : 'Suggeriment opcional; el camp lliure de matèria continua disponible més avall.',
    chooseSubject: language === 'en' ? 'Choose a subject' : 'Tria una matèria',
    otherSubject: language === 'en' ? 'Other / write manually' : 'Altra / escriure manualment',
    writeSubject: language === 'en' ? 'Write a subject' : 'Escriu una matèria',
    invalidFile: language === 'en' ? 'Invalid file' : language === 'ca' ? 'Fitxer no vàlid' : 'Fitxer no vàlid',
    duplicateSuffix: language === 'en' ? ' (copy)' : language === 'ca' ? ' (còpia)' : ' (còpia)',
    copied: language === 'en' ? 'Copied' : 'Copiat',
    copyFailed: language === 'en' ? 'Could not copy' : 'No s’ha pogut copiar',
    editableHint: language === 'en' ? 'Edit the generated prompt before copying or saving it.' : language === 'ca' ? 'Edita el prompt generat abans de copiar-lo o desar-lo.' : 'Edita el prompt generat abans de copiar-lo o guardar-lo.',
    fullscreen: language === 'en' ? 'Full screen' : 'Pantalla completa',
    exitFullscreen: language === 'en' ? 'Exit full screen' : 'Eixir de pantalla completa',
    updateAvailable: language === 'en' ? 'A new version of the application is available.' : language === 'ca' ? 'Hi ha una nova versió de l’aplicació.' : 'Hi ha una nova versió de l’aplicació.',
    updateButton: language === 'en' ? 'Update application' : language === 'ca' ? 'Actualitza l’aplicació' : 'Actualitza l’aplicació',
    edit: language === 'en' ? 'Edit' : language === 'ca' ? 'Edita' : 'Edita',
    placeholderCourse: language === 'en' ? 'E.g. 4th Primary' : 'Ex. 4t de Primària',
    placeholderSubject: language === 'en' ? 'E.g. Natural Sciences' : 'Ex. Ciències Naturals',
    placeholderTopic: language === 'en' ? 'E.g. Ecosystems in our local environment' : 'Ex. Els ecosistemes del nostre entorn',
    placeholderObjectives: language === 'en' ? 'E.g. Understand, explain and apply the key ideas...' : 'Ex. Comprendre, explicar i aplicar les idees clau...',
    placeholderContext: language === 'en' ? 'E.g. Heterogeneous group; some students need reading support...' : 'Ex. Grup heterogeni; part de l’alumnat necessita suport lector...',
    placeholderConstraints: language === 'en' ? 'E.g. One 45-minute session, everyday materials, no personal data...' : 'Ex. Una sessió de 45 minuts, materials quotidians, sense dades personals...',
    placeholderQualityCriteria: language === 'en' ? 'E.g. Practical, inclusive, observable and easy to review...' : 'Ex. Pràctic, inclusiu, observable i fàcil de revisar...',
    placeholderRole: language === 'en' ? 'E.g. Primary teacher specialising in active learning' : 'Ex. Docent de Primària especialista en aprenentatge actiu',
    placeholderTask: language === 'en' ? 'E.g. Design a sequence of activities with a final product...' : 'Ex. Dissenya una seqüència d’activitats amb un producte final...',
    placeholderActivity: language === 'en' ? 'E.g. Debate on responsible use of social media' : 'Ex. Debat sobre l’ús responsable de les xarxes socials',
    placeholderCriteria: language === 'en' ? 'E.g. Argumentation, evidence and respectful participation...' : 'Ex. Argumentació, ús d’evidències i participació respectuosa...',
    level: language === 'en' ? 'Educational level' : language === 'ca' ? 'Nivell educatiu' : 'Nivell educatiu',
    course: language === 'en' ? 'Course' : 'Curs', subject: language === 'en' ? 'Subject' : 'Matèria', topic: language === 'en' ? 'Topic' : 'Tema',
    objectives: language === 'en' ? 'Objectives' : 'Objectius', methodology: language === 'en' ? 'Methodology' : 'Metodologia', duration: language === 'en' ? 'Duration' : 'Duració', resources: language === 'en' ? 'Available resources' : 'Recursos disponibles', format: language === 'en' ? 'Output format' : 'Format d’eixida', activity: language === 'en' ? 'Activity' : 'Activitat', criteria: language === 'en' ? 'Criteria' : 'Criteris', levels: language === 'en' ? 'Performance levels' : 'Nivells de rendiment', activityType: language === 'en' ? 'Activity type' : 'Tipus d’activitat', role: language === 'en' ? 'Role' : 'Rol', context: language === 'en' ? 'Group and situation context' : 'Context del grup i la situació', task: language === 'en' ? 'Task' : 'Tasca', constraints: language === 'en' ? 'Constraints and limits' : 'Restriccions i límits', qualityCriteria: language === 'en' ? 'Quality criteria' : 'Criteris de qualitat',
    newCategoryPlaceholder: language === 'en' ? 'Write a new category (optional)' : language === 'ca' ? 'Escriu una categoria nova (opcional)' : 'Escriu una categoria nova (opcional)',
    titlePlaceholder: language === 'en' ? 'E.g. Arduino rubric 4ESO' : 'Ex. Rúbrica Arduino 4ESO',
    tagsPlaceholder: language === 'en' ? '4ESO, Technology, PBL' : '4ESO, Tecnologia, ABP',
    templateLearningSituation: language === 'en' ? 'Learning situation' : language === 'ca' ? 'Situació d’aprenentatge' : 'Situació d’aprenentatge',
    templateLesson: language === 'en' ? 'Class session' : language === 'ca' ? 'Sessió de classe' : 'Sessió de classe',
    templateSequence: language === 'en' ? 'Teaching sequence' : language === 'ca' ? 'Seqüència didàctica' : 'Seqüència didàctica',
    templateCompetencyActivity: language === 'en' ? 'Competency-based activity' : language === 'ca' ? 'Activitat competencial' : 'Activitat competencial',
    templateProject: language === 'en' ? 'PBL project' : language === 'ca' ? 'Projecte ABP' : 'Projecte ABP',
    templateChallenge: language === 'en' ? 'Problem or challenge' : language === 'ca' ? 'Problema o repte' : 'Problema o repte',
    templateRubric: language === 'en' ? 'Rubric' : 'Rúbrica',
    templateChecklist: language === 'en' ? 'Checklist' : language === 'ca' ? 'Llista de verificació' : 'Llista de coteig',
    templateRatingScale: language === 'en' ? 'Rating scale' : language === 'es' ? 'Escala de valoración' : 'Escala de valoració',
    templateSystematicObservation: language === 'en' ? 'Systematic observation' : language === 'es' ? 'Observación sistemática' : 'Observació sistemàtica',
    templatePortfolio: language === 'en' ? 'Portfolio' : 'Portafolis',
    templateProduction: language === 'en' ? 'Student production' : language === 'es' ? 'Producción' : 'Producció',
    templateWrittenTest: language === 'en' ? 'Written test' : language === 'es' ? 'Prueba escrita' : 'Prova escrita',
    templateProduct: language === 'en' ? 'Learning product' : language === 'es' ? 'Producto' : 'Producte',
    templatePresentation: language === 'en' ? 'Presentation' : language === 'es' ? 'Exposición' : 'Exposició',
    templateH5p: language === 'en' ? 'H5P activity' : 'Activitat H5P',
    templateFree: language === 'en' ? 'Free builder' : language === 'ca' ? 'Constructor lliure' : 'Constructor lliure'
    ,templateFeedback: language === 'en' ? 'Formative feedback' : language === 'es' ? 'Feedback formativo' : 'Feedback formatiu'
    ,templateThreeLevels: language === 'en' ? 'One material, three levels' : language === 'es' ? 'Un material, tres niveles' : 'Un material, tres nivells'
    ,templateFamilyNote: language === 'en' ? 'Family communication' : language === 'es' ? 'Comunicación a familias' : 'Comunicació a les famílies'
    ,templateEasyReading: language === 'en' ? 'Easy reading' : language === 'es' ? 'Lectura fácil' : 'Lectura fàcil'
    ,templateBiasCheck: language === 'en' ? 'Bias check' : language === 'es' ? 'Revisión de sesgos' : 'Revisió de biaixos'
    ,templateGlossarySupport: language === 'en' ? 'Glossary and visual supports' : language === 'es' ? 'Glosario y apoyos visuales' : 'Glossari i suports visuals'
    ,templateTutoringScript: language === 'en' ? 'Tutoring script' : language === 'es' ? 'Guion de tutoría' : 'Guió de tutoria'
    ,sourceText: language === 'en' ? 'Source text' : language === 'es' ? 'Texto de partida' : 'Text de partida'
    ,placeholderSourceText: language === 'en' ? 'Paste the text you want to adapt here (no personal data)...' : language === 'es' ? 'Pega aquí el texto que quieres adaptar (sin datos personales)...' : 'Enganxa ací el text que vols adaptar (sense dades personals)...'
    ,login: language === 'en' ? 'Sign in' : language === 'es' ? 'Iniciar sesión' : 'Inicia sessió'
    ,logout: language === 'en' ? 'Sign out' : language === 'es' ? 'Cerrar sesión' : 'Tanca la sessió'
    ,sync: language === 'en' ? 'Sync library' : language === 'es' ? 'Sincronizar biblioteca' : 'Sincronitza la biblioteca'
    ,syncDownloaded: language === 'en' ? 'Your online library is ready.' : language === 'es' ? 'Tu biblioteca online ya está disponible.' : 'La teua biblioteca en línia ja està disponible.'
    ,syncUploaded: language === 'en' ? 'Local prompts uploaded to your library.' : language === 'es' ? 'Los prompts locales se han subido a tu biblioteca.' : 'Els prompts locals s’han pujat a la teua biblioteca.'
    ,syncFailed: language === 'en' ? 'The library could not be synchronized.' : language === 'es' ? 'No se ha podido sincronizar la biblioteca.' : 'No s’ha pogut sincronitzar la biblioteca.'
    ,formMode: language === 'en' ? 'Form mode' : language === 'es' ? 'Modo del formulario' : 'Mode del formulari'
    ,simpleMode: language === 'en' ? 'Simple' : language === 'es' ? 'Sencillo' : 'Senzill'
    ,advancedMode: language === 'en' ? 'Advanced' : language === 'es' ? 'Avanzado' : 'Avançat'
    ,simpleModeHint: language === 'en' ? 'Start with the essential fields. You can add detail later.' : language === 'es' ? 'Empieza con los campos esenciales. Puedes añadir detalle después.' : 'Comença amb els camps essencials. Pots afegir detalls després.'
    ,advancedModeHint: language === 'en' ? 'All fields are visible for more precise prompts.' : language === 'es' ? 'Todos los campos están visibles para crear prompts más precisos.' : 'Tots els camps estan visibles per a crear prompts més precisos.'
  })
}
export function detectLanguage(): Language { const value = localStorage.getItem('edutictac-language'); if (value === 'es'||value === 'ca'||value === 'ca-valencia'||value === 'en') return value; const browser = navigator.language.toLowerCase(); return browser.startsWith('en')?'en':browser.startsWith('ca')?'ca': 'es' }
