import type { PromptTemplate } from './types'
export const templates: PromptTemplate[] = [
  { id: 'learning-situation', category: 'planning', icon: '◎', fields: [{id:'level',type:'select',options:['Infantil','Primaria','ESO','Bachillerato','Formación Profesional','Universidad','Otro']},{id:'course',type:'text'},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'methodology',type:'multiselect',options:['Aprendizaje basado en proyectos','Aprendizaje cooperativo','Aprendizaje basado en problemas','DUA','Investigación']},{id:'duration',type:'select',options:['15 minutos','30 minutos','45 minutos','55 minutos','Una sesión','Varias sesiones']},{id:'resources',type:'multiselect',options:['Ordenadores','Tablets','Proyector','Pizarra digital','Material manipulativo','Sin tecnología']},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla']}] },
  { id: 'lesson', category: 'planning', icon: '◷', fields: [{id:'level',type:'select',options:['Infantil','Primaria','ESO','Bachillerato','FP','Universidad']},{id:'course',type:'text'},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'duration',type:'select',options:['15 minutos','30 minutos','45 minutos','55 minutos','Una sesión']},{id:'resources',type:'multiselect',options:['Ordenadores','Tablets','Proyector','Pizarra digital','Sin tecnología']},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla']}] },
  { id: 'sequence', category: 'planning', icon: '☷', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP','Universidad']},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'duration',type:'select',options:['Una sesión','Varias sesiones','Una semana','Varias semanas']},{id:'methodology',type:'multiselect',options:['ABP','Cooperativo','Gamificación','Investigación','Aprendizaje servicio']},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla']}] },
  { id: 'competency-activity', category: 'activities', icon: '✦', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'methodology',type:'multiselect',options:['Cooperativo','Retos','Gamificación','Trabajo individual']},{id:'resources',type:'multiselect',options:['Ordenadores','Material manipulativo','Sin tecnología']},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla']}] },
  { id: 'project', category: 'activities', icon: '⌂', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'duration',type:'select',options:['Una semana','Varias semanas']},{id:'resources',type:'multiselect',options:['Ordenadores','Robots','Laboratorio','Material manipulativo']},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla']}] },
  { id: 'challenge', category: 'activities', icon: '◇', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'methodology',type:'multiselect',options:['Aprendizaje basado en problemas','Retos','Pensamiento crítico']},{id:'outputFormat',type:'select',options:['Texto','Markdown']}] },
  { id: 'rubric', category: 'assessment', icon: '▤', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'activity',type:'text'},{id:'criteria',type:'textarea'},{id:'levels',type:'select',options:['3','4','5']},{id:'outputFormat',type:'select',options:['Tabla Markdown','Tabla HTML','Texto']}] },
  { id: 'checklist', category: 'assessment', icon: '☑', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'activity',type:'text'},{id:'criteria',type:'textarea'},{id:'outputFormat',type:'select',options:['Tabla Markdown','Lista']}] },
  { id: 'h5p', category: 'digital', icon: '▣', fields: [{id:'level',type:'select',options:['Primaria','ESO','Bachillerato','FP']},{id:'subject',type:'text'},{id:'topic',type:'text'},{id:'objectives',type:'textarea'},{id:'activityType',type:'select',options:['Quiz','Arrastrar y soltar','Vídeo interactivo','Tarjetas']},{id:'outputFormat',type:'select',options:['H5P','Markdown']}] },
  { id: 'free', category: 'free', icon: '✎', fields: [{id:'role',type:'text'},{id:'context',type:'textarea'},{id:'task',type:'textarea'},{id:'constraints',type:'textarea'},{id:'outputFormat',type:'select',options:['Texto','Markdown','Tabla','JSON','HTML']}] }
]

export const categoryIds = ['all','planning','activities','assessment','adaptation','content','digital','communication','free']
